name: mkdocs 
on:
  push:
    branches:
      - master 
      - main
    paths:
      - 'docs/**'
      - 'examples/**'
      - 'notenbildung/**'
      - 'mkdocs.yml'
      - '.github/workflows/mkdocs.yml'
      - 'generate_latex_metadata.sh'
      - 'generate_markdown_from_latex.sh'
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc pandoc-citeproc
        shell: bash

      - name: Check for changes in LaTeX file
        id: check_changes
        run: |
          echo "changed=$(git diff --name-only HEAD^ HEAD | grep -Eq 'docs/files/tex' && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT

      - name: Create temporary tex ./docs/files
        run: |
          ./generate_latex_metadata.sh
        shell: bash

      - name: Generate markdown version of notentransparenz
        run: |
          ./generate_markdown_from_latex.sh
        shell: bash

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: notentransparenz.tex
          working_directory: ./docs/files/tex

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: |
          echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
          echo "build_doc_date=$(date -u '+%d.%m.%Y')" >> $GITHUB_ENV
          echo "REPO_COMMIT=$(git log -1 --pretty=format:%H)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: |
          pip install -r requirements_docs.txt
      - run: |
          mike deploy --branch gh-pages --update-aliases --push ${{ github.sha }} latest
          mike set-default --branch gh-pages --push latest
