name: mkdocs 
on:
  push:
    branches:
      - master 
      - main
    paths:
      - 'docs/**'
      - 'examples/**'
      - 'mkdocs.yml'
      - '.github/workflows/mkdocs.yml'
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for changes in LaTeX file
        id: check_changes
        run: |
          echo "changed=$(git diff --name-only HEAD^ HEAD | grep -Eq 'docs/files/(notentransparenz.tex|references.bib)' && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT

      - name: Create temporary tex ./docs/files and set CNAME
        run: |
          ./generate_latex_metadata.sh
          echo "transparenz.hilberg.eu" > ./docs/CNAME
        shell: bash

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: notentransparenz.tex
          working_directory: ./docs/files

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: |
          echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
          echo "build_doc_date=$(date -u '+%d.%m.%Y')" >> $GITHUB_ENV

      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: |
          pip install mkdocs-material mkdocs-macros-plugin mkdocs-glightbox mkdocs-pdf-export-plugin
      - run: mkdocs gh-deploy --force
